name: 🚀 Deploy Frontend

on:
  push:
    branches:
      - master

jobs:
  deploy-client:
    name: 🎉 Deploy Frontend
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Checkout Latest Code
        uses: actions/checkout@v3

      - name: Use Node.js v22.11.0
        uses: actions/setup-node@v2
        with:
          node-version: '22.11.0'

      - name: 🔨 Install Dependencies & Build Frontend
        run: |
          cd client
          npm install
          npm run build  # Generates build in 'client/dist'

      - name: 📂 Sync Frontend Files to cPanel
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.GIT_CPANEL_REACT_SERVER }}
          username: ${{ secrets.GIT_CPANEL_REACT_USER }}
          password: ${{ secrets.GIT_CPANEL_REACT_PWD }}
          protocol: ${{ secrets.GIT_CPANEL_REACT_PROTOCOL }}
          local-dir: ./client/dist/  # Frontend build files
          # remote-dir: /home4/thehyper/public_html/blogs/client/  # Remote directory on cPanel
